// TODO change to FBV.

export const healing = [
{ l: '1 Peter 2:24', t: "He himself bore our sins in his body on the tree, that we might die to sin and live to righteousness. By his wounds, you have been healed." },
{ l: '3 John 1:2', t: "Dear friend, I pray that you may enjoy good health and that all may go well with you" },
{ l: 'Acts 10:38', t: "God anointed Jesus of Nazareth with the Holy Spirit and power, and how he went around doing good and healing all who were under the power of the devil, because God was with him." },
{ l: 'Acts 19:11–12', t: "God was doing extraordinary miracles by the hands of Paul, so that even handkerchiefs or aprons that had touched his skin were carried away to the sick, and their diseases left them and the evil spirits came out of them." },
{ l: 'Acts 3:16', t: "By faith in the name of Jesus, this man whom you see and know was made strong. It is Jesus’ name and the faith that comes through him that has completely healed him, as you can all see." },
{ l: 'Acts 4:22', t: "For the man who was miraculously healed was over forty years old." },
{ l: 'Acts 4:30', t: "Stretch out your hand to heal and perform signs and wonders through the name of your holy servant Jesus." },
{ l: 'Acts 5:16', t: "And the people also gathered from the towns around Jerusalem, bringing the sick and those afflicted with unclean spirits, and they were all healed." },
{ l: 'Deuteronomy 7:15', t: "And the LORD will take away from you all sickness, and none of the evil diseases of Egypt, which you knew, will he inflict on you." },
{ l: 'Exodus 15:26', t: "I am the Lord who heals you." },
{ l: 'Exodus 23:25', t: "You shall serve the Lord your God, and he will bless your bread and your water, and I will take sickness away from you." },
{ l: 'Hosea 6:1', t: "Come, let us return to the Lord. He has torn us to pieces but he will heal us; he has injured us but he will bind up our wounds." },
{ l: 'Isaiah 40:31', t: "But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint." },
{ l: 'Isaiah 41:10', t: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand." },
{ l: 'Isaiah 53:4', t: "Surely he took up our pain and bore our suffering, yet we considered him punished by God, stricken by him, and afflicted." },
{ l: 'Isaiah 53:5', t: "But he was pierced for our transgressions; he was crushed for our iniquities; upon him was the chastisement that brought us peace, and with his wounds, we are healed." },
{ l: 'Isaiah 57:18-19', t: "'I have seen his ways, but I will heal him; I will lead him and restore comfort to him and his mourners, creating the fruit of the lips. Peace, peace, to the far and to the near,' says the Lord, 'and I will heal him.'" },
{ l: 'Isaiah 58:11', t: "And the LORD will guide you continually and satisfy your desire in scorched places and make your bones strong" },
{ l: 'Isaiah 58:8', t: "Then shall your light break forth like the dawn, and your healing shall spring up speedily; your righteousness shall go before you; the glory of the Lord shall be your rear guard." },
{ l: 'James 5:14-15', t: "Is anyone among you sick? Let him call for the elders of the church, and let them pray over him, anointing him with oil in the name of the Lord. And the prayer of faith will save the one who is sick, and the Lord will raise him up." },
{ l: 'James 5:16', t: "Therefore, confess your sins to one another and pray for one another, that you may be healed. The prayer of a righteous person has great power as it is working." },
{ l: 'Jeremiah 17:14', t: "Heal me, LORD, and I will be healed; save me and I will be saved, for you are the one I praise." },
{ l: 'Jeremiah 30:17', t: "For I will restore health to you, and your wounds I will heal, declares the Lord." },
{ l: 'Jeremiah 33:6', t: "Behold, I will bring to it health and healing, and I will heal them and reveal to them an abundance of prosperity and security." },
{ l: 'Job 5:18', t: "For he wounds, but he also binds up; he injures, but his hands also heal." },
{ l: 'Job 8:21', t: "He will yet fill your mouth with laughter and your lips with shouts of joy." },
{ l: 'John 10:10', t: "The thief comes only to steal and kill and destroy; I have come that they may have life and have it to the full." },
{ l: 'John 14:12', t: "Truly, truly, I say to you, whoever believes in me will also do the works that I do; and greater works than these will he do, because I am going to the Father." },
{ l: 'John 5:13', t: "The man who was healed had no idea who it was, for Jesus had slipped away into the crowd that was there." },
{ l: 'Lamentations 3:22-23', t: "The steadfast love of the Lord never ceases; his mercies never come to an end. They are new every morning; great is your faithfulness." },
{ l: 'Luke 10:9', t: "Heal the sick who are there and tell them, ‘The kingdom of God has come near to you.’" },
{ l: 'Luke 18:42', t: "And Jesus said to him, 'Receive your sight; your faith has healed you.'" },
{ l: 'Luke 4:40', t: "At sunset, the people brought to Jesus all who had various kinds of sickness, and laying his hands on each one, he healed them." },
{ l: 'Luke 5:17', t: "And the power of the Lord was with him to heal." },
{ l: 'Luke 6:19', t: "And the people all tried to touch him, because power was coming from him and healing them all." },
{ l: 'Luke 8:50', t: "But when Jesus heard it, he answered him, 'Do not fear; only believe, and she will be well.'" },
{ l: 'Luke 9:1', t: "When Jesus had called the Twelve together, he gave them power and authority to drive out all demons and to cure diseases." },
{ l: 'Luke 9:2', t: "And he sent them out to proclaim the kingdom of God and to heal the sick." },
{ l: 'Luke 9:6', t: "So they set out and went from village to village, proclaiming the good news and healing people everywhere." },
{ l: 'Malachi 4:2', t: "But for you who fear my name, the sun of righteousness shall rise with healing in its wings. You shall go out leaping like calves from the stall." },
{ l: 'Mark 10:52', t: "And Jesus said to him, 'Go your way; your faith has made you well.' And immediately he recovered his sight and followed him on the way." },
{ l: 'Mark 11:24', t: "Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours." },
{ l: 'Mark 1:40-42', t: "And a leper came to him, imploring him, and kneeling said to him, 'If you will, you can make me clean.' Moved with pity, he stretched out his hand and touched him and said to him, 'I will; be clean.' And immediately the leprosy left him, and he was made clean." },
{ l: 'Mark 5:24-29', t: "And a great crowd followed him and thronged about him. And there was a woman who had had a discharge of blood for twelve years, and who had suffered much under many physicians, and had spent all that she had, and was no better but rather grew worse. She had heard the reports about Jesus and came up behind him in the crowd and touched his garment. For she said, 'If I touch even his garments, I will be made well.' And immediately the flow of blood dried up, and she felt in her body that she was healed of her disease." },
{ l: 'Mark 5:34', t: "And he said to her, 'Daughter, your faith has made you well; go in peace, and be healed of your disease.'" },
{ l: 'Matthew 10:1', t: "Jesus called his twelve disciples to him and gave them authority to drive out impure spirits and to heal every disease and sickness." },
{ l: 'Matthew 10:8', t: "Heal the sick, raise the dead, cleanse those who have leprosy, drive out demons. Freely you have received; freely give." },
{ l: 'Matthew 12:15', t: "Aware of this, Jesus withdrew from that place. A large crowd followed him, and he healed all who were ill." },
{ l: 'Matthew 4:23', t: "And he went throughout all Galilee, teaching in their synagogues and proclaiming the gospel of the kingdom and healing every disease and every affliction among the people." },
{ l: 'Matthew 8:13', t: "And Jesus said to the centurion, 'Go; let it be done for you as you have believed.' And the servant was healed at that very moment." },
{ l: 'Matthew 8:16', t: "When evening came, many who were demon-possessed were brought to him, and he drove out the spirits with a word and healed all the sick." },
{ l: 'Matthew 8:17', t: "He took up our infirmities and bore our diseases." },
{ l: 'Matthew 8:3', t: "Jesus reached out his hand and touched the man. “I am willing,” he said. “Be clean!” Immediately he was cleansed of his leprosy." },
{ l: 'Matthew 8:8', t: "The centurion replied, “Lord, I do not deserve to have you come under my roof. But just say the word, and my servant will be healed." },
{ l: 'Matthew 9:22', t: "Jesus turned, and seeing her he said, 'Take heart, daughter; your faith has made you well.' And instantly the woman was made well." },
{ l: 'Matthew 9:29', t: "Then he touched their eyes, saying, 'According to your faith be it done to you.'" },
{ l: 'Matthew 9:35', t: "And Jesus went throughout all the cities and villages, teaching in their synagogues and proclaiming the gospel of the kingdom and healing every disease and every affliction." },
{ l: 'Philippians 4:19', t: "And my God will meet all your needs according to the riches of his glory in Christ Jesus." },
{ l: 'Proverbs 14:30', t: "A heart at peace gives life to the body, but envy rots the bones." },
{ l: 'Proverbs 16:24', t: "Gracious words are like a honeycomb, sweetness to the soul and health to the body." },
{ l: 'Proverbs 23:15-16', t: "My son, if your heart is wise, my heart will be glad; even my body will rejoice. Yes, my bones will rest securely." },
{ l: 'Proverbs 3:8', t: "This will bring health to your body and nourishment to your bones." },
{ l: 'Proverbs 4:20-22', t: "My son, be attentive to my words; incline your ear to my sayings. Let them not escape from your sight; keep them within your heart. For they are life to those who find them, and healing to all their flesh." },
{ l: 'Psalm 103:2-3', t: "Bless the Lord, O my soul, and forget not all his benefits, who forgives all your iniquity, who heals all your diseases." },
{ l: 'Psalm 107:19-20', t: "Then they cried to the Lord in their trouble, and he delivered them from their distress. He sent out his word and healed them, and delivered them from their destruction." },
{ l: 'Psalm 121:7-8', t: "The LORD will protect you from all evil; He will keep your soul. The LORD will guard your going out and your coming in From this time forth and forever." },
{ l: 'Psalm 145:18', t: "The Lord is near to all who call on him, to all who call on him in truth." },
{ l: 'Psalm 147:3', t: "He heals the brokenhearted and binds up their wounds." },
{ l: 'Psalm 16:9', t: "Therefore my heart is glad, and my whole being rejoices; my flesh also dwells securely." },
{ l: 'Psalm 28:7', t: "The LORD is my strength and my shield; my heart trusts in him, and he helps me." },
{ l: 'Psalm 30:2', t: "O Lord my God, I cried to you for help, and you have healed me." },
{ l: 'Psalm 31:7', t: "I will be glad and rejoice in your love, for you saw my affliction and knew the anguish of my soul." },
{ l: 'Psalm 34:17-18', t: "When the righteous cry for help, the Lord hears and delivers them out of all their troubles. The Lord is near to the brokenhearted and saves the crushed in spirit." },
{ l: 'Psalm 37:5', t: "Commit your way to the Lord; trust in him, and he will act." },
{ l: 'Psalm 41:1-3', t: "Blessed is the one who considers the poor! In the day of trouble, the Lord delivers him; the Lord protects him and keeps him alive; he is called blessed in the land; you do not give him up to the will of his enemies. The Lord sustains him on his sickbed; in his illness, you restore him to full health." },
{ l: 'Psalm 55:22', t: "Cast your cares on the Lord and he will sustain you; he will never let the righteous be shaken." },
{ l: 'Psalm 63:7', t: "For you have been my help, and in the shadow of your wings, I will sing for joy." },
{ l: 'Psalm 6:2', t: "Have mercy on me, Lord, for I am faint; heal me, Lord, for my bones are in agony." },
{ l: 'Revelation 21:4', t: "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away." },
];
