// TODO change to FBV.

const healing = [
{ l: '1 Peter 2:24', t: "He himself bore our sins in his body on the tree, that we might die to sin and live to righteousness. By his wounds, you have been healed." },
{ l: '3 John 1:2', t: "Dear friend, I pray that you may enjoy good health and that all may go well with you" },
{ l: 'Acts 10:38', t: "God anointed Jesus of Nazareth with the Holy Spirit and power, and how he went around doing good and healing all who were under the power of the devil, because God was with him." },
{ l: 'Acts 19:11–12', t: "God was doing extraordinary miracles by the hands of Paul, so that even handkerchiefs or aprons that had touched his skin were carried away to the sick, and their diseases left them and the evil spirits came out of them." },
{ l: 'Acts 3:16', t: "By faith in the name of Jesus, this man whom you see and know was made strong. It is Jesus’ name and the faith that comes through him that has completely healed him, as you can all see." },
{ l: 'Acts 4:22', t: "For the man who was miraculously healed was over forty years old." },
{ l: 'Acts 4:30', t: "Stretch out your hand to heal and perform signs and wonders through the name of your holy servant Jesus." },
{ l: 'Acts 5:16', t: "And the people also gathered from the towns around Jerusalem, bringing the sick and those afflicted with unclean spirits, and they were all healed." },
{ l: 'Deuteronomy 7:15', t: "And the LORD will take away from you all sickness, and none of the evil diseases of Egypt, which you knew, will he inflict on you." },
{ l: 'Exodus 15:26', t: "I am the Lord who heals you." },
{ l: 'Exodus 23:25', t: "You shall serve the Lord your God, and he will bless your bread and your water, and I will take sickness away from you." },
{ l: 'Hosea 6:1', t: "Come, let us return to the Lord. He has torn us to pieces but he will heal us; he has injured us but he will bind up our wounds." },
{ l: 'Isaiah 40:31', t: "But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint." },
{ l: 'Isaiah 41:10', t: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand." },
{ l: 'Isaiah 53:4', t: "Surely he took up our pain and bore our suffering, yet we considered him punished by God, stricken by him, and afflicted." },
{ l: 'Isaiah 53:5', t: "But he was pierced for our transgressions; he was crushed for our iniquities; upon him was the chastisement that brought us peace, and with his wounds, we are healed." },
{ l: 'Isaiah 57:18-19', t: "'I have seen his ways, but I will heal him; I will lead him and restore comfort to him and his mourners, creating the fruit of the lips. Peace, peace, to the far and to the near,' says the Lord, 'and I will heal him.'" },
{ l: 'Isaiah 58:11', t: "And the LORD will guide you continually and satisfy your desire in scorched places and make your bones strong." },
{ l: 'Isaiah 58:8', t: "Then shall your light break forth like the dawn, and your healing shall spring up speedily; your righteousness shall go before you; the glory of the Lord shall be your rear guard." },
{ l: 'James 5:14-15', t: "Is anyone among you sick? Let him call for the elders of the church, and let them pray over him, anointing him with oil in the name of the Lord. And the prayer of faith will save the one who is sick, and the Lord will raise him up." },
{ l: 'James 5:16', t: "Therefore, confess your sins to one another and pray for one another, that you may be healed. The prayer of a righteous person has great power as it is working." },
{ l: 'Jeremiah 17:14', t: "Heal me, LORD, and I will be healed; save me and I will be saved, for you are the one I praise." },
{ l: 'Jeremiah 30:17', t: "For I will restore health to you, and your wounds I will heal, declares the Lord." },
{ l: 'Jeremiah 33:6', t: "Behold, I will bring to it health and healing, and I will heal them and reveal to them an abundance of prosperity and security." },
{ l: 'Job 5:18', t: "For he wounds, but he also binds up; he injures, but his hands also heal." },
{ l: 'Job 8:21', t: "He will yet fill your mouth with laughter and your lips with shouts of joy." },
{ l: 'John 10:10', t: "The thief comes only to steal and kill and destroy; I have come that they may have life and have it to the full." },
{ l: 'John 14:12', t: "Truly, truly, I say to you, whoever believes in me will also do the works that I do; and greater works than these will he do, because I am going to the Father." },
{ l: 'John 5:13', t: "The man who was healed had no idea who it was, for Jesus had slipped away into the crowd that was there." },
{ l: 'Lamentations 3:22-23', t: "The steadfast love of the Lord never ceases; his mercies never come to an end. They are new every morning; great is your faithfulness." },
{ l: 'Luke 10:9', t: "Heal the sick who are there and tell them, ‘The kingdom of God has come near to you.’" },
{ l: 'Luke 18:42', t: "And Jesus said to him, 'Receive your sight; your faith has healed you.'" },
{ l: 'Luke 4:40', t: "At sunset, the people brought to Jesus all who had various kinds of sickness, and laying his hands on each one, he healed them." },
{ l: 'Luke 5:17', t: "And the power of the Lord was with him to heal." },
{ l: 'Luke 6:19', t: "And the people all tried to touch him, because power was coming from him and healing them all." },
{ l: 'Luke 8:50', t: "But when Jesus heard it, he answered him, 'Do not fear; only believe, and she will be well.'" },
{ l: 'Luke 9:1', t: "When Jesus had called the Twelve together, he gave them power and authority to drive out all demons and to cure diseases." },
{ l: 'Luke 9:2', t: "And he sent them out to proclaim the kingdom of God and to heal the sick." },
{ l: 'Luke 9:6', t: "So they set out and went from village to village, proclaiming the good news and healing people everywhere." },
{ l: 'Malachi 4:2', t: "But for you who fear my name, the sun of righteousness shall rise with healing in its wings. You shall go out leaping like calves from the stall." },
{ l: 'Mark 10:52', t: "And Jesus said to him, 'Go your way; your faith has made you well.' And immediately he recovered his sight and followed him on the way." },
{ l: 'Mark 11:24', t: "Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours." },
{ l: 'Mark 1:40-42', t: "And a leper came to him, imploring him, and kneeling said to him, 'If you will, you can make me clean.' Moved with pity, he stretched out his hand and touched him and said to him, 'I will; be clean.' And immediately the leprosy left him, and he was made clean." },
{ l: 'Mark 5:24-29', t: "And a great crowd followed him and thronged about him. And there was a woman who had had a discharge of blood for twelve years, and who had suffered much under many physicians, and had spent all that she had, and was no better but rather grew worse. She had heard the reports about Jesus and came up behind him in the crowd and touched his garment. For she said, 'If I touch even his garments, I will be made well.' And immediately the flow of blood dried up, and she felt in her body that she was healed of her disease." },
{ l: 'Mark 5:34', t: "And he said to her, 'Daughter, your faith has made you well; go in peace, and be healed of your disease.'" },
{ l: 'Matthew 10:1', t: "Jesus called his twelve disciples to him and gave them authority to drive out impure spirits and to heal every disease and sickness." },
{ l: 'Matthew 10:8', t: "Heal the sick, raise the dead, cleanse those who have leprosy, drive out demons. Freely you have received; freely give." },
{ l: 'Matthew 12:15', t: "Aware of this, Jesus withdrew from that place. A large crowd followed him, and he healed all who were ill." },
{ l: 'Matthew 4:23', t: "And he went throughout all Galilee, teaching in their synagogues and proclaiming the gospel of the kingdom and healing every disease and every affliction among the people." },
{ l: 'Matthew 8:13', t: "And Jesus said to the centurion, 'Go; let it be done for you as you have believed.' And the servant was healed at that very moment." },
{ l: 'Matthew 8:16', t: "When evening came, many who were demon-possessed were brought to him, and he drove out the spirits with a word and healed all the sick." },
{ l: 'Matthew 8:17', t: "He took up our infirmities and bore our diseases." },
{ l: 'Matthew 8:3', t: "Jesus reached out his hand and touched the man. “I am willing,” he said. “Be clean!” Immediately he was cleansed of his leprosy." },
{ l: 'Matthew 8:8', t: "The centurion replied, “Lord, I do not deserve to have you come under my roof. But just say the word, and my servant will be healed." },
{ l: 'Matthew 9:22', t: "Jesus turned, and seeing her he said, 'Take heart, daughter; your faith has made you well.' And instantly the woman was made well." },
{ l: 'Matthew 9:29', t: "Then he touched their eyes, saying, 'According to your faith be it done to you.'" },
{ l: 'Matthew 9:35', t: "And Jesus went throughout all the cities and villages, teaching in their synagogues and proclaiming the gospel of the kingdom and healing every disease and every affliction." },
{ l: 'Philippians 4:19', t: "And my God will meet all your needs according to the riches of his glory in Christ Jesus." },
{ l: 'Proverbs 14:30', t: "A heart at peace gives life to the body, but envy rots the bones." },
{ l: 'Proverbs 16:24', t: "Gracious words are like a honeycomb, sweetness to the soul and health to the body." },
{ l: 'Proverbs 23:15-16', t: "My son, if your heart is wise, my heart will be glad; even my body will rejoice. Yes, my bones will rest securely." },
{ l: 'Proverbs 3:8', t: "This will bring health to your body and nourishment to your bones." },
{ l: 'Proverbs 4:20-22', t: "My son, be attentive to my words; incline your ear to my sayings. Let them not escape from your sight; keep them within your heart. For they are life to those who find them, and healing to all their flesh." },
{ l: 'Psalm 103:2-3', t: "Bless the Lord, O my soul, and forget not all his benefits, who forgives all your iniquity, who heals all your diseases." },
{ l: 'Psalm 103:5', t: "He fills my life with all that's good; he makes me young again, strong as an eagle." },
{ l: 'Psalm 107:19-20', t: "Then they cried to the Lord in their trouble, and he delivered them from their distress. He sent out his word and healed them, and delivered them from their destruction." },
{ l: 'Psalm 121:7-8', t: "The LORD will protect you from all evil; He will keep your soul. The LORD will guard your going out and your coming in From this time forth and forever." },
{ l: 'Psalm 145:18', t: "The Lord is near to all who call on him, to all who call on him in truth." },
{ l: 'Psalm 147:3', t: "He heals the brokenhearted and binds up their wounds." },
{ l: 'Psalm 16:9', t: "Therefore my heart is glad, and my whole being rejoices; my flesh also dwells securely." },
{ l: 'Psalm 28:7', t: "The LORD is my strength and my shield; my heart trusts in him, and he helps me." },
{ l: 'Psalm 30:2', t: "O Lord my God, I cried to you for help, and you have healed me." },
{ l: 'Psalm 31:7', t: "I will be glad and rejoice in your love, for you saw my affliction and knew the anguish of my soul." },
{ l: 'Psalm 34:17-18', t: "When the righteous cry for help, the Lord hears and delivers them out of all their troubles. The Lord is near to the brokenhearted and saves the crushed in spirit." },
{ l: 'Psalm 37:5', t: "Commit your way to the Lord; trust in him, and he will act." },
{ l: 'Psalm 41:1-3', t: "Blessed is the one who considers the poor! In the day of trouble, the Lord delivers him; the Lord protects him and keeps him alive; he is called blessed in the land; you do not give him up to the will of his enemies. The Lord sustains him on his sickbed; in his illness, you restore him to full health." },
{ l: 'Psalm 55:22', t: "Cast your cares on the Lord and he will sustain you; he will never let the righteous be shaken." },
{ l: 'Psalm 63:7', t: "For you have been my help, and in the shadow of your wings, I will sing for joy." },
{ l: 'Psalm 6:2', t: "Have mercy on me, Lord, for I am faint; heal me, Lord, for my bones are in agony." },
{ l: 'Revelation 21:4', t: "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away." },
];

const holySpiritAndSanctification = [
{ l: '1 Corinthians 6:11', t: "You have been made clean and holy. You have been made right in the name of the Lord Jesus Christ, and in the Spirit of our God." },
{ l: '1 Corinthians 6:19', t: "Don't you know that your body is a temple of the Holy Spirit that is within you, that you received from God?" },
{ l: '1 Peter 1:2', t: "You were chosen by God the Father in his wisdom, made holy by the Spirit, so that you might obey Jesus Christ and be sprinkled with his blood." },
{ l: '1 Thessalonians 4:3-8', t: "What God wants is for you to live holy lives. So stay away from sexual immorality in order that each of you may control yourselves in a way that is holy and respectful, not indulging passionate lust like the heathen who have no knowledge of God. Don't cheat or take advantage of another Christian in these matters, for the Lord is the one who executes justice in all such things, as we've already clearly explained to you, and warned you about. For God did not call us to live impure lives, but holy lives. So anyone who rejects this position isn't just rejecting what a human being is saying; they are rejecting God, who gives his Holy Spirit to you." },
{ l: '1 Thessalonians 5:23-24', t: "May the God of peace himself make you completely holy, and may your whole being—body, mind and spirit—be kept blameless for when our Lord Jesus Christ returns. The one who calls you is trustworthy, and he will do this." },
{ l: '2 Corinthians 3:17-18 ', t: "Now the Lord is the Spirit, and wherever the Spirit of the Lord is, there's freedom. So all of us, with our faces unveiled, see and reflect the glory of the Lord as in a mirror. We are being transformed into the same mirror image, whose glory grows brighter and brighter. This is what the Lord the Spirit does." },
{ l: '2 Thessalonians 2:13', t: "The Spirit who makes you right as you trust in the truth." },
{ l: '2 Timothy 1:14', t: "Guard the truth that was entrusted to you through the Holy Spirit who lives in us." },
{ l: 'Acts 1:8', t: "You will be given power when the Holy Spirit comes upon you" },
{ l: 'Ephesians 1:13-14', t: "because you trusted in him you were stamped with the seal of the Holy Spirit's promise, 14which is a down-payment on our inheritance when God redeems what he's kept safe for himself—us, who will praise and give him glory!" },
{ l: 'Ephesians 3:16', t: "Out of his wealth of glory he may strengthen you in your innermost being with power through his Spirit." },
{ l: 'Ephesians 4:30', t: "Don't disappoint the Holy Spirit of God that marked you as belonging to him until the day of redemption." },
{ l: 'Ephesians 5:18', t: "Don't get drunk on wine which will wreck your life, but be filled with the Spirit." },
{ l: 'Ephesians 5:25-27', t: "Christ loved the church and gave himself for it. He made it holy, he made it clean by washing in the water of the word, so that he could make the church his own, with no flaw or blemish or any kind of fault, but holy and blameless." },
{ l: 'Ezekiel 36:26-27 ', t: "I will give you a new mind and I will put a new spirit inside you. I will take away your stubborn mind and I will give you a loving mind. I will put my Spirit inside you so you will follow my laws and remember to do what I tell you." },
{ l: 'Galatians 5:16-17', t: "My advice is to walk by the Spirit. Don't satisfy the desires of your sinful human nature. 17For the desires of the sinful nature are opposed to the Spirit, and the desires of the Spirit are opposed to the sinful nature. They fight one another, so you don't do what you want to do." },
{ l: 'Galatians 5:22', t: "The Spirit produces fruit such as love, joy, peace, patience, kindness, goodness, trust, gentleness, and self-control" },
{ l: 'Genesis 32:26', t: "I won't let you go unless you bless me (Jacob wrestling with Jesus)" },
{ l: 'Hebrews 10:14', t: "He has set right forever those who are being made holy." },
{ l: 'Hebrews 13:20-21', t: "May the God of peace who raised our Lord Jesus, the great shepherd of the sheep, from the dead, with the blood of an eternal agreement — may he provide you with all that is good so you can do his will. May he work in us, doing everything that pleases him" },
{ l: 'Hebrews 4:16', t: "Go confidently to God on his throne of grace so we can receive mercy, and discover grace to help us when we really need it" },
{ l: 'Isaiah 55:11-13', t: "The words I say don't come back to me unfulfilled, they accomplish what I want — they successfully achieve my purpose. You will live happily, taught the ways of peace. Mountains and hills will celebrate, singing beside you; and all the trees will clap their hands! Cypress trees will grow instead of thorn bushes; myrtle trees will grow instead of brambles. This is to confirm the Lord's reputation" },
{ l: 'John 14:16-18', t: "I will ask the Father, and he will give you another Comforter, the Spirit of truth, who will always be with you. The world cannot accept him because it isn't looking for him and doesn't know him. But you know him because he lives with you and will be in you. I will not abandon you like orphans." },
{ l: 'John 16:13-14', t: "When the Spirit of truth comes, he will teach you the whole truth. He doesn't speak for himself, but he only says what he hears, and he will tell you what's going to happen. He brings me glory for he teaches you whatever he receives from me." },
{ l: 'John 17:17', t: "Make them holy by the truth; your word is truth. (Jesus praying to God the Father for us)" },
{ l: 'Luke 11:13', t: "If you, even though you are evil, still know to give good gifts to your children, how much more will the heavenly Father give the Holy Spirit to those who ask him?" },
{ l: 'Luke 18:5-8', t: "This widow is so annoying I'll make sure she receives justice. Then she won't wear me out by her coming to see me so often. Listen to what even an unjust judge decided,” said the Lord. Don't you think that God will make sure his chosen people receive justice, those who cry out to him day and night? Do you think he will make them wait? No, I tell you, he will give them justice quickly." },
{ l: 'Philippians 1:6', t: "I'm absolutely sure that God who began this good work in you will continue working and bring it to a successful conclusion when Jesus Christ returns." },
{ l: 'Philippians 2:13', t: "For it's God who is working within you, creating the will and the ability to do what he wants you to do." },
{ l: 'Psalm 51:10-11', t: "Create a pure mind in me, God, and make me trustworthy again. Don't expel me from your presence; don't take away your Holy Spirit from me." },
{ l: 'Romans 12:2', t: "Don't follow the ways of this world; instead be transformed by the spiritual renewal of your mind so you can demonstrate what God's will really is—good, pleasing, and perfect." },
{ l: 'Romans 15:15-16', t: "God gave me grace to be a minister of Christ Jesus to the foreigners, like a priest sharing God's good news, so that they could become an acceptable offering, made holy by the Holy Spirit." },
{ l: 'Romans 7:14-15', t: "We realize that the law is spiritual; but I'm all-too-human, a slave to sin. I really don't understand what I'm doing. I do the things I don't want to do, and what I hate doing, that's what I do!" },
{ l: 'Romans 8:13-14', t: "For if you live under the control of your sinful nature, you're going to die. But if you follow the way of the Spirit, putting to death the evil things you do, then you will live. All those who are led by the Spirit of God are God's children." },
{ l: 'Romans 8:2', t: "The law of the Spirit of life in Christ Jesus has set me free from the law of sin and death." },
{ l: 'Romans 8:26', t: "The Spirit helps us in our weakness. We don't know how to speak with God, but the Spirit himself intercedes with and through us by groans that can't be put into words." },
{ l: 'Romans 8:5-6', t: "Those who follow their sinful nature are preoccupied with sinful things, but those who follow the Spirit concentrate on spiritual things. The sinful human mind results in death, but having the mind led by the Spirit results in life and peace." },
{ l: 'Romans 8:9', t: "But you're not following your sinful nature, but the Spirit—if it's true that the Spirit of God is living in you." },
{ l: 'Titus 3:4-6', t: "He saved us, not because of anything good that we've done, but because of his mercy. He did this through the cleansing of rebirth and renewal of the Holy Spirit, which he poured out on us abundantly." },
];

const blessing = [
{ l: '1 Chronicles 4:10', t: `Jabez begged the God of Israel, “Please bless me and expand my borders! Be with me and keep me safe from harm so I won't have pain.” And God gave him what he asked for.` },
{ l: '1 Chronicles 13:14', t: `The Ark of God remained in Obed-edom's home for three months, and the Lord blessed Obed-edom's household and all that he had.` },
{ l: '1 Chronicles 29:11-12', t: `Lord, yours is the greatness, the power, the glory, the splendor, and the majesty, for everything in heaven and on earth is yours. Lord, yours is the kingdom, and you are admired as ruler of all. 12Riches and honor come from you and you reign supreme. You possess power and might, and have the ability to make people great and to give strength to all.` },
{ l: '1 Chronicles 29:28', t: `David died at a good old age, having lived a long life, blessed with wealth and honor.` },
{ l: '1 Corinthians 3:8', t: `The one planting and the one watering have the same goal, and both will be rewarded.` },
{ l: '1 Corinthians 9:9-10', t: `In the law of Moses it's written, “Don't muzzle the ox when it's threshing out the grain.” Was God just thinking about oxen? 10Wasn't he directing this at us? Surely this was written for us—for anyone who plows should plow in hope and anyone who threshes should hope to share in the harvest.` },
{ l: '1 Kings 2:3', t: `Do what God orders you to do, and follow his ways. Keep his rules, his commands, and his laws and regulations, as written in the Law of Moses, so you may be successful in everything you do, and in everything you give your attention to. ` },
{ l: '1 Kings 3:13', t: `I am also giving you what you did not ask for, wealth and status—so much so that no king will compare to you for the whole of your life.` },
{ l: '1 Kings 4:20', t: `Judah and Israel had become as numerous as the sand on the seashore. They ate, they drank, they were happy.` },
{ l: '1 Kings 10:23', t: `King Solomon was greater than any other king on earth in wealth and wisdom.` },
{ l: '1 Kings 17:4', t: `I have ordered ravens to bring you food` },
{ l: '1 Kings 17:9', t: `I have given instructions to a widow there to provide you with food.` },
{ l: '1 Samuel 2:7-8', t: `The Lord makes some poor, but others rich; he brings some down, but he lifts others up. He helps the poor up from the dust; he raises the lowborn from the trash pile and seats them with the upper class in places of honor.` },
{ l: '1 Samuel 18:14', t: `David was very successful in everything he did, because the Lord was with him.` },
{ l: '1 Samuel 25:6', t: `Tell him, ‘I wish you a long life! Peace to you and your family, and may everything you do prosper.` },
{ l: '1 Timothy 6:8', t: `But if we have food and clothes then that's enough for us.` },
{ l: '1 Timothy 6:10', t: `For the desire to be rich leads to many kinds of evil results. Some of those who longed for this have turned away from the truth, and have hurt themselves, experiencing a lot of pain.` },
{ l: '1 Timothy 6:17', t: `Warn those who are rich in the present world not to become proud. Tell them not to place their trust in wealth that is so insecure but in God who so freely gives us everything for our enjoyment. ` },
{ l: '2 Chronicles 1:11–12', t: `God told Solomon: “Because this is what you really wanted, and you didn't ask for wealth, possessions, or honor, or the death of those who hate you, or for a long life, but instead you asked for wisdom and knowledge so you can rule with justice my people that I have made you king over; 12wisdom and knowledge is given to you. I will give you wealth, possessions, and honor as well, much more than any king who came before you has had, or who comes after you will ever have.` },
{ l: '2 Chronicles 1:15', t: `The king made silver and gold as plentiful in Jerusalem as stones` },
{ l: '2 Chronicles 17:5', t: `The Lord made Jehoshaphat's hold on the kingdom secure, and all the people of Judah paid their dues to him. As a result he became very wealthy and highly honored.` },
{ l: '2 Chronicles 26:5', t: `As long as he followed the Lord, God made him successful.` },
{ l: '2 Chronicles 31:10', t: `Ever since the people began to bring their contributions into the Lord's Temple, we have had enough to eat and plenty to spare. Because the Lord has blessed his people there is so much left over.` },
{ l: '2 Chronicles 31:21', t: `Hezekiah was sincere in his commitment to God. So he was successful in all he did.` },
{ l: '2 Chronicles 32:27-29', t: `Hezekiah was very rich and highly honored, and he built treasury storerooms to hold silver, gold, precious stones, spices, shields, and all kinds of valuable things. He constructed buildings to store supplies of grain, new wine, and olive oil, and stalls for all kinds of animals, including cattle and sheep. He built many towns, and he owned large herds of cattle and flocks of sheep, for God had made him very wealthy.` },
{ l: '2 Corinthians 8:2', t: `Even though they have suffered terrible trouble, they are overflowing with happiness; and even though they are very poor, they are also overflowing in their generosity.` },
{ l: '2 Corinthians 8:9', t: `For you know the grace of our Lord Jesus Christ. Even though he was rich, he became poor for you, so that through his poverty you could become rich. (before + after context: financial generosity)` },
{ l: '2 Corinthians 9:6-13', t: `I want to remind you of this: If you only sow a little, you'll only reap a little; if you sow plenty, you'll reap plenty. Everybody should give as they've already decided—not reluctantly, or because they have to, for God loves those who give with a cheerful spirit. God is able to graciously provide you with everything, so that you will always have all you need—with plenty to help others too. As Scripture says, “He gives generously to the poor; his generosity is everlasting.” God, who provides seed to the sower and gives bread for food, will provide and multiply your “seed” and increase your harvest of generosity. You will be made rich in every way so that you can always be very generous, and your generosity will lead others to be grateful to God. When you serve in this way, not only are the needs of God's people met, but also many will give grateful thanks to God. By giving this offering you show your true nature` },
{ l: '2 Samuel 6:11', t: `The Ark of the Lord remained in Obed-edom's home for three months, and the Lord blessed Obed-edom's whole household.` },
{ l: '2 Samuel 7:28-29', t: `Lord Almighty, you are God! Your words are truth, and you are the one who has promised these good things to your servant. 29So now, please bless your servant's house that it may continue in your presence forever.` },
{ l: 'Acts 4:33-34', t: `God greatly blessed them all. None of them needed anything because those who had lands or properties sold them.` },
{ l: 'Acts 14:17', t: `Even so he still provided evidence of himself by doing good, sending you rain from heaven and crops in their seasons, providing all the food you need, and filling you with happiness.` },
{ l: 'Acts 20:35', t: `Work to help those who are weak, remembering the words of the Lord Jesus: ‘It is more blessed to give than to receive.’”` },
{ l: 'Amos 9:13–15', t: `Look! The time is coming, says the Lord, when the reaper will overtake the plowman, and the one who treads the grapes will overtake the one who sows the seed. The mountains will drip with sweet wine, and flow from all the hills. I will bring my people back from captivity, and they will rebuild the ruined cities, and they shall live in them. They shall plant vineyards and drink their wine; they will plant gardens and eat the fruit they produce. I will plant them in their own land, and they shall never be uprooted again from the land I have given them, declares the Lord your God.` },
{ l: 'Colossians 1:9', t: `We haven't stopped praying for you from the time we heard about you, asking God to give you understanding of what he wants you to do` },
{ l: 'Daniel 6:28', t: `Daniel experienced good success during the reigns of Darius and Cyrus the Persian.` },
{ l: 'Deuteronomy 1:10', t: `The Lord your God has increased your numbers so much that today there are as many of you as there are stars in the sky.` },
{ l: 'Deuteronomy 2:7', t: `The Lord your God has blessed you in everything you've done. He has looked after you during your journey through this large desert. The Lord your God has been with you for these forty years, and you haven't lacked anything.` },
{ l: 'Deuteronomy 6:3', t: `Be careful to observe them (Gods rules), so that you may do well and have many descendants in a land flowing with milk and honey, just as the Lord, the God of your forefathers, promised you.` },
{ l: 'Deuteronomy 7:13-15', t: `He will love you and bless you and give you many descendants. He will bless your children and the crops your land produces—your grain, new wine, and olive oil, the calves of your cattle herds and the lambs of your flocks—in the land that he promised your forefathers to give you. You will be blessed more than any other nation; none of you will be childless, and none of your livestock will fail to have young. The Lord will keep you from having any kind of sickness. He will not let you have any of the terrible diseases you saw in Egypt, but he will let all who hate you suffer from them.` },
{ l: 'Deuteronomy 8:1', t: `You must take care to follow every commandment I am giving you today, so that you may live and have many descendants, and go in and take over the country the Lord promised to give to your forefathers.` },
{ l: 'Deuteronomy 8:7-10', t: `The Lord your God is taking you to a good country. It's a land of streams and pools and springs that flow through the valleys and down the hills; It's a land that produces wheat, barley, vines, fig trees, pomegranates, olive oil and honey. It's a land where you won't run out of food, where you will have everything you need; a land whose rocks contain iron ore and whose hills can be mined for copper. When you eat and are full, make sure you thank the Lord your God for the good land that he's given you.` },
{ l: 'Deuteronomy 8:18', t: `It's the Lord your God who gives you the ability to become rich, in order to fulfill his agreement he promised to your forefathers that still exists today.` },
{ l: 'Deuteronomy 11:11-12', t: `ere in the country that you are crossing the Jordan to take over is a land of mountains and valleys that receives plenty of rain It is a land that the Lord your God takes care of. The Lord your God is always watching over it, all year long.` },
{ l: 'Deuteronomy 11:13-15', t: `if you love the Lord your God and worship him with all your mind and with all your being, then I will send rain for your land at the right time, rain in autumn and spring, so that you can harvest your grain, new wine, and olive oil. I will also provide grass in the fields for your livestock. You will have more than enough to eat.` },
{ l: 'Deuteronomy 11:21', t: `As long as the earth lasts, you and your children may have long lives in the country the Lord promised to give your forefathers.` },
{ l: 'Deuteronomy 12:7', t: `In the presence of the Lord your God, you and your families will eat and celebrate everything you've worked for, because the Lord your God has blessed you.` },
{ l: 'Deuteronomy 13:17-18', t: `He will be merciful to you, showing you compassion, and giving you many descendants as he promised to your forefathers, because you are obeying the Lord your God.` },
{ l: 'Deuteronomy 14:28-29', t: `Every third year, collect a tenth of all your produce for that year and store it in your town. This way the Levites (who don't have any share in the allotment of land), the foreigners, the orphans, and the widows in your town will be provided with what they need. The Lord your God will bless you in everything you do.` },
{ l: 'Deuteronomy 15:4', t: `You shouldn't have poor people among you, for the Lord will really bless you in the country that the Lord your God is giving you to own.` },
{ l: 'Deuteronomy 15:6', t: `The Lord your God is going to bless you as he promised. You will lend money to many nations but you won't need to borrow from any of them` },
{ l: 'Deuteronomy 15:10', t: `Give and give again to them (the poor), and don't feel irritated when you give. When you give generously the Lord your God will bless you in all your work and in everything you decide to do.` },
{ l: 'Deuteronomy 16:10', t: `Honor the Lord your God by giving him a freewill offering, depending on just how much the Lord your God has blessed you.` },
{ l: 'Deuteronomy 16:15', t: `Celebrate this Festival for seven days to honor the Lord your God in the place he will choose, because the Lord your God will bless your whole harvest and everything you do` },
{ l: 'Deuteronomy 26:12', t: `Once you've finished storing up a tenth of all your crops in the third year (the year of the tithe), you shall give it to the Levites, the foreigners, the orphans, and the widows, so they will have enough to eat in your towns.` },
{ l: 'Deuteronomy 26:13-15', t: `you are to make this declaration in the presence of the Lord your God: “I have brought the holy tithe and I have given it to the Levite, the foreigners, the orphans, and the widows as you have ordered me to do. ... Please look down from your home in heaven, and bless your people the Israelites and the country you have given us as you promised` },
{ l: 'Deuteronomy 28:2-11', t: `You will have all the following blessings and even more, if you do what the Lord your God says. You will be blessed when you're in the town; you will be blessed when you're in the countryside. You will be blessed with many children. You will be blessed with good harvests. You will be blessed with livestock—your cattle will have many calves, and your sheep will have many lambs. You will be blessed with plenty of bread. You will be blessed wherever you go and in everything you do. The Lord will defeat the enemies who come to attack you. They will come at you from one direction, but they will scatter seven different ways. The Lord will bless your income and everything you do. The Lord your God will bless you in the country he is giving you. The Lord will make you his holy people, just as he promised you, if you obey the Lord your God's commandments and follow his ways. Then everyone on earth will see that the Lord has chosen you to be his, and they will be afraid of you. The Lord will make you very prosperous.` },
{ l: 'Deuteronomy 28:13', t: `The Lord will put you in first place, not the last. You will only go up, never down, as long as you listen to and follow carefully the commandments of the Lord` },
{ l: 'Deuteronomy 29:9', t: `Follow the terms of this agreement in order that you may be successful in everything you do.` },
{ l: 'Deuteronomy 30:5', t: `The Lord your God will bring you home to the country that belonged to your forefathers and you will own it again. He will make you successful` },
{ l: 'Deuteronomy 30:9', t: `The Lord your God will make you successful in everything you do, you will have children, your livestock will be productive, and you will have good harvests.` },
{ l: 'Deuteronomy 30:16', t: `Love the Lord your God, to follow his ways, and to keep his commandments, rules, and regulations, so you can live and grow in number, and so the Lord your God may bless you in the country that you are entering and will own.` },
{ l: 'Deuteronomy 33:13-14', t: `May the Lord bless his land with the best gifts of heaven—with the dew and water from the depths below; with the best crops ripened by the sun and the best produce.` },
{ l: 'Deuteronomy 33:23', t: `Naphtali is really favored, full of the Lord's blessing. He shall take over the land to the west and south.` },
{ l: 'Ecclesiastes 5:12', t: `Those who work hard sleep well, whether they have a little to eat or plenty, but the rich own so much they don't get any rest.` },
{ l: 'Ecclesiastes 5:13-14', t: `People who hoard money damage themselves. 14They put their money into bad investments and lose everything.` },
{ l: 'Ecclesiastes 5:19', t: `Everyone to whom God gives wealth and possessions he also gives the ability to enjoy these gifts, to be grateful for what they are given, and to enjoy the work they do. This is also God's gift to us.` },
{ l: 'Ecclesiastes 9:11', t: `The wise do not always have food, intelligent people do not always make money, and those who are clever do not always win favor. Time and chance affect all of them.` },
{ l: 'Ecclesiastes 9:7–8', t: `Go ahead and eat your food, and enjoy it. Drink your wine with a happy heart. That's what God intends that you should do. Always wear smart clothes and look good.` },
{ l: 'Ecclesiastes 10:19', t: `Money provides for all needs.` },
{ l: 'Ephesians 2:10', t: `We're the product of what God does, created in Christ Jesus to do good, which God already planned that we should do.` },
{ l: 'Exodus 1:7', t: `The Israelites had many children and their numbers increased rapidly` },
{ l: 'Exodus 3:8', t: `I have come down to rescue them [my people] from Egyptian oppression and to take them up from that country to a productive, wide-open land—a land flowing with milk and honey.` },
{ l: 'Exodus 3:21-22', t: `I will make the Egyptians treat you well as a people, so when you go you won't leave empty-handed. Every woman will ask her neighbor as well as any woman living in her house for silver and gold jewelry and clothing, and put them on your sons and daughters. In this way you will take the wealth of the Egyptians with you.”` },
{ l: 'Exodus 16:4', t: `4The Lord told Moses, “Just watch! I'm going to rain down bread from heaven for you!` },
{ l: 'Exodus 16:12', t: `“I have heard the complaints of the Israelites. Tell them, ‘In the evening you will eat meat, and in the morning you will have as much bread as you want. Then you will know that I am the Lord your God.’”` },
{ l: 'Exodus 23:25–26', t: `You are to worship the Lord your God, and he will bless your food and water. I will make sure none of you fall sick. No woman will have a miscarriage or be without children. I will make sure you live long lives.` },
{ l: 'Ezekiel 34:14', t: `I will provide them with good pasture and places to graze in the high mountains of Israel.` },
{ l: 'Ezekiel 34:26-27', t: `I will bless them everywhere around my hill. I will send rain at the right time. They will be showers of blessing. The trees in the orchards will produce their fruit; the earth will grow its crops; and my flock will live in safety in their country. Then they will know that I am the Lord, when I break their yokes of slavery, and set them free from those who made them slaves.` },
{ l: 'Ezekiel 36:11', t: `The number of your people will grow— they will have many children. The animals too will have many young. You mountains, I will make sure that you are inhabited just as you used to be, and I will make you more prosperous than you were before. Then you will know that I am the Lord.` },
{ l: 'Ezekiel 36:29-30', t: ` I will make sure you have plenty of grain. I won't send you any famines. I will also make sure you have good harvests from your orchards and fields.` },
{ l: 'Ezekiel 37:26', t: `This will be an everlasting agreement. I will make them secure and increase their numbers.` },
{ l: 'Galatians 3:14', t: `Through Christ Jesus the blessing of Abraham could come to the foreigners as well, and we could receive the promise of the Spirit by trusting God.` },
{ l: 'Genesis 1:26', t: `God said, “Let us make human beings in our image who are like us.` },
{ l: 'Genesis 9:1', t: `God blessed Noah and his sons, and told them, “Reproduce, increase, and spread throughout the earth!` },
{ l: 'Genesis 9:7', t: `Reproduce, increase, and spread throughout the earth—have many descendants!”` },
{ l: 'Genesis 12:2-3', t: `I will make you the ancestor of a great nation and I will bless you. I will make sure you have a great reputation and that you are a blessing to others. I will bless those who bless you; I will curse those who curse you. Everyone on earth will be blessed through you.”` },
{ l: 'Genesis 17:8', t: `I will give you and your descendants the whole country of Canaan—where you've been living as a foreigner—as land to own forever, and I will be their God.”` },
{ l: 'Genesis 22:8-14', t: `“God will provide the lamb for the burnt offering, my son,” Abraham replied, and they went on walking ... Abraham looked up and saw a ram caught by its horns in some bushes. He brought the ram over and sacrificed it as a burnt offering in place of his son. Abraham called the place “The Lord will Provide.”` },
{ l: 'Genesis 24:1', t: `Abraham by now was old, really old, and the Lord had blessed him in every possible way.` },
{ l: 'Genesis 26:22', t: `He had another well dug. This time there was no argument so he named the well, “Freedom,” saying, “Now the Lord has given us freedom to expand and be successful in this land.”` },
{ l: 'Genesis 27:28', t: `“May God use the dew of heaven and fertile land to give you rich harvests of grain and new wine!` },
{ l: 'Genesis 28:3', t: `God Almighty bless you and may your descendants be so numerous that you become the ancestor of many nations.` },
{ l: 'Genesis 30:27', t: `“Please be so kind as to stay,” Laban replied, “because I have discovered that the Lord has blessed me because of you.”` },
{ l: 'Genesis 30:43', t: `Jacob became an extremely rich man with large flocks` },
{ l: 'Genesis 35:11', t: `Then God said, “I am God Almighty! Reproduce, increase, and you will become a nation—in fact a group of nations—and kings will be among your descendants.` },
{ l: 'Genesis 39:2-3', t: `The Lord was with Joseph and made him successful. He lived in his Egyptian master's house. His master noticed that the Lord was with him and made him successful in everything he did.` },
{ l: 'Genesis 39:5', t: `The Lord blessed Potiphar's household because of Joseph. The Lord blessed everything he had, whether in his house or in his fields.` },
{ l: 'Genesis 39:23', t: `The chief jailer didn't bother with anything for Joseph took care of it all, for the Lord was with him and made him successful.` },
{ l: 'Genesis 41:52', t: `His second son he named Ephraim, because he said, “God has made me fruitful` },
{ l: 'Genesis 48:4', t: `I will make you prosperous and make your descendants so numerous that you will become the ancestor of many nations, and I will give this land to your descendants to own forever.’` },
{ l: 'Genesis 49:25', t: `The God of your father will help you and the Almighty will bless you with blessings from the heavens above, with blessings from the depths below, with blessings for many children.` },
{ l: 'Haggai 2:7-8', t: `I will fill this house with glory, says the Lord Almighty. The silver is mine, and the gold is mine, declares the Lord Almighty.` },
{ l: 'Haggai 2:19', t: `The seed is still in the barn. The vine, the fig tree, the pomegranate tree, and the olive tree have not yet given fruit. But from this day on I will bless you.` },
{ l: 'Hebrews 13:5', t: `Don't love money; be content with what you have. God himself has said, “I'll never let you down; I'll never give up on you.”` },
{ l: 'Hosea 2:21-22', t: `The earth will answer the grain, and the new wine, and the olive oil, and they shall answer, ‘Jezreel’ (God sows).` },
{ l: 'Isaiah 1:18-19', t: `Come on, let's argue this out, says the Lord. Even though your sins are like scarlet, they will become white like snow. Even though they are red like crimson, they will become like wool. If you really want this, and if you do as you're told, then you yourselves will eat the best things that the land produces.` },
{ l: 'Isaiah 19:24-25', t: `At that time Israel will be the third part of this alliance, joining with Egypt and Assyria, a blessing to the whole of the earth. The Lord Almighty will bless them, saying, “Blessed be Egypt, my people, Assyria, the creation of my hands, and Israel, my special possession.”` },
{ l: 'Isaiah 30:23', t: `He will send rain when you sow, and the land will produce great harvests. At that time your cattle will feed in rich pastures.` },
{ l: 'Isaiah 33:16', t: `They will live on high; they will be protected by the mountain fortresses; they will always be provided with food and will always have water.` },
{ l: 'Isaiah 48:18', t: `If you had only listened carefully to what I told you! Then your blessings would have flowed like a river, and goodness would have washed over you like the waves of the sea. ` },
{ l: 'Isaiah 51:2-3', t: `Look back at Abraham your father, and Sarah who gave birth to you. When I called him, he was only one man, but then I blessed him and he had many descendants. The Lord will care for Zion and feel sorry about all her ruined places. ` },
{ l: 'Isaiah 54:2-3', t: `Make the tent where you live bigger; stretch the fabric to enlarge your home. Don't try and save space—extend your tent cords and make your tent pegs stronger. You're going to be spreading out right and left; your descendants will take over the land of other nations and live in towns that were once abandoned.` },
{ l: 'Isaiah 58:11', t: `The Lord will always lead you; he will give you all you need in a desolate land` },
{ l: 'Isaiah 60:5-6', t: `Then you will see and shine brilliantly, your heart will beat wildly for joy, for the riches that cross the sea, the wealth of the nations, will be brought to you. ... All the people of Sheba will come to you carrying gold and frankincense, shouting praises to the Lord.` },
{ l: 'Isaiah 61:6-7', t: `You will enjoy the wealth of nations and be proud that you have it. Instead of shame you will receive a double blessing; instead of insults, you will be happy to have a double amount of land given to you, and your joy will last forever.` },
{ l: 'James 1:5', t: `If any of you need wisdom, ask God, who gives generously to everyone without holding back.` },
{ l: 'James 1:9-10', t: `Believers who are born poor should take pride in the high position they've been given, while the rich should “boast” in the humble position they now have` },
{ l: 'James 1:25', t: `But if you look to the perfect law of freedom and follow it, not as someone who just listens and then forgets, but as someone who acts on it—then you will be blessed in what you do.` },
{ l: 'James 2:6', t: `Isn't it the rich who oppress you and drag you before the courts?` },
{ l: 'James 5:1-6', t: `Come on, you rich people! You should weep and wail for all the problems that are coming your way! Your wealth is ruined, and your clothes have been eaten by moths. Your gold and your silver are corroded, and this corrosion will be evidence against you, eating away your flesh like fire. You hoarded up your wealth in these last days. Look, the wages of your farm workers that you cheated are crying out against you—the cries of the farm workers have reached the ears of the Lord Almighty. You've enjoyed a life of luxury here on earth, full of self-indulgent pleasure, fattening yourselves up for the day of slaughter! You have condemned and killed the innocent who didn't even resist you.` },
{ l: 'James 5:11', t: `Those who endure are blessed. You've heard about the patience of Job, and you've seen how the Lord brought this to a positive conclusion—for the Lord is full of compassion and mercy.` },
{ l: 'Jeremiah 5:24', t: `You didn't think to say, “We should appreciate the Lord our God, who sends the autumn and spring rains at the right time, who makes sure we can have a harvest every year.”` },
{ l: 'Jeremiah 9:23', t: `This is what the Lord says: The wise shouldn't boast about their wisdom. The strong shouldn't boast about their strength. The rich shouldn't boast about their riches.` },
{ l: 'Jeremiah 17:7-8', t: `Blessed are those who trust in the Lord, who put their confidence in him. They are like trees planted by water, sending out roots toward the stream. They don't panic when it gets hot; their leaves are always green. They don't worry during a time of drought—they go on producing fruit.` },
{ l: 'Jeremiah 23:3', t: `I [the Lord] myself will gather what's left of my flock from all the countries where I exiled them, and I will bring them back to their pasture, where they will increase in number.` },
{ l: 'Jeremiah 29:11-12', t: `I know what I intend to do for you, declares the Lord. I plan good things for you and not bad. I'm going to give you a future and a hope. Then you will call for my help, you will come and pray to me, and I will answer you. ` },
{ l: 'Jeremiah 30:19', t: `People will be singing songs of thanks, the sounds of celebration. I will increase their number—they will not become less. I will honor them—they will not be treated as insignificant.` },
{ l: 'Jeremiah 31:12', t: `They will return and celebrate with happy shouts on Mount Zion; their faces will beam over the Lord's wonderful gifts—the grain, new wine, and olive oil, and the young of their flocks and herds. Their life will be like a well-watered garden; and they won't ever be depressed again.` },
{ l: 'Job 1:9-10', t: `“Is it for nothing that Job respects God?” Satan answered. “You've placed a protective fence around him and his family—in fact around everything he has. You have blessed everything he does. His flocks and herds have increased so much they fill the whole land!` },
{ l: 'Job 42:10-12', t: `The Lord restored Job's prosperity when he prayed for his friends, and gave him twice as much as he had before. ... The Lord blessed the last part of Job's life more than the first part. Now he owned 14,000 sheep, 6,000 camels, 1,000 teams of oxen, and 1,000 female donkeys.` },
{ l: 'Joel 2:23-25', t: `Celebrate and be happy in the Lord your God because he has given you rain to show his goodness. As before he sends the autumn and the spring rains. The threshing floors will be full of grain, the vats will overflow with new wine and olive oil. “I will give back to you what you lost over the years` },
{ l: 'Joel 2:26', t: `You will have plenty to eat, and you will be satisfied, and you will praise the name of the Lord your God who has done miracles for you.` },
{ l: 'John 10:10', t: `The thief comes only to steal, kill, and destroy. I've come to bring you life, life full to overflowing.` },
{ l: 'John 15:16', t: `You didn't choose me, I chose you. I have given you the responsibility to go and produce lasting fruit. So the Father will give you whatever you ask in my name.` },
{ l: 'Joshua 1:7', t: `Just be strong and very brave, and be sure to obey all the law that my servant Moses instructed you to follow. Don't turn aside from it, either to the right or to the left, so that you may be successful in everything you do.` },
{ l: 'Joshua 1:8', t: `Keep on reminding the people about the law. Meditate on it day and night, so you can be sure to do what it requires. Then you will be successful and prosper in what you do.` },
{ l: 'Joshua 24:12-13', t: `But I handed them over to you to defeat. And I sent the hornet before you to drive out the two kings of the Amorites. You did not win using your swords or your bows! I gave you a land you didn't work for and towns you didn't build. Now you live in them and eat from vineyards and olive groves you didn't plant.’` },
{ l: 'Judges 18:10', t: `God has given you a place where there's no shortage of anything!` },
{ l: 'Leviticus 25:20-21', t: `But if you ask, ‘What are we going to do in the seventh year if we do not sow or harvest our crops?’ I will bless you in the sixth year, so that the land will produce a crop that will be enough for three years.` },
{ l: 'Leviticus 26:3-5', t: `If you follow my rules and keep my regulations, I will make sure it rains at the right time so that the ground will grow good crops and the fruit trees will be productive. Your time of threshing will last right up to the grape harvest, and the grape harvest until the time you have to sow again. You will have more than enough to eat and you will live in safety in your land.` },
{ l: 'Leviticus 26:9-10', t: `I will come to help you, so you will reproduce and increase in numbers, and I will confirm my agreement with you. You'll still be eating your old stock of grain when you need to get rid of it so you can store the new grain.` },
{ l: 'Luke 6:24', t: `How sad are you who are rich, for you have already received your reward.` },
{ l: 'Luke 6:38', t: `Give, and you will be given generously in return. When what you're given is measured out, it's pressed down so more can be added, spilling out over the top, pouring into your lap! For how much you give will determine how much you receive.` },
{ l: 'Luke 11:3', t: `Give us every day the food we need.` },
{ l: 'Luke 12:15', t: `Beware of all greedy thoughts and actions, for a person's life isn't summed up by all the things they own.` },
{ l: 'Luke 12:20-21', t: `God said to him, ‘You foolish man! Your life will be demanded back this very night, and then who will get everything you've stored up?’ This is what happens to people who hoard up wealth for themselves but are not rich as far as God is concerned.”` },
{ l: 'Luke 12:22-24', t: `Jesus told his disciples, “That's why I tell you don't worry about life, about what to eat, or about what clothes you should wear. Life is about more than food, and the body is about more than wearing clothes. Look at the ravens. They don't sow or reap, they don't have any storerooms or barns, but God feeds them. And you're far more valuable than birds! ` },
{ l: 'Luke 12:27–31', t: `Think of the lilies and how they grow. They don't work, and they don't spin thread for clothes, but I tell you, not even Solomon in all his glory was as beautifully dressed as one of them. So if God clothes the fields with such beautiful flowers, which are here today but gone tomorrow when they are burned in a fire to heat an oven, how much more will God clothe you, you who have so little trust! Don't be concerned about what you're going to eat or drink—don't worry about it. These are all things that people in the world worry about, but your Father knows you need them. Search for God's kingdom, and you'll be given these things as well. ` },
{ l: 'Luke 16:9', t: `I tell you, use the wealth of this world to make friends for yourselves so that when it's gone, you'll be welcomed into an eternal home.` },
{ l: 'Luke 16:13', t: `You can't serve both God and Money.` },
{ l: 'Luke 18:24-25', t: `When he saw his reaction, Jesus said, “How difficult it is for the rich to enter the kingdom of God! It's easier for a camel to go through the eye of a needle than for a rich person to enter the kingdom of God.”` },
{ l: 'Luke 18:29–30', t: `“I tell you the truth,” Jesus told them, “anybody who leaves behind their home, wife, brothers, parents, or children for the sake of God's kingdom will receive so much more in this life, and eternal life in the world to come.”` },
{ l: 'Malachi 3:7-10', t: `Return to me, and I will return to you, says the Lord Almighty. But you ask, “How should we return?” Should people defraud God? Yet you are defrauding me! But you ask, “How have we defrauded you?” In tithes and offerings. You are under a curse, for you and the whole nation are defrauding me. Bring the full tithe into the storehouse so that there will be food in my Temple. Put me to the test in this, says the Lord Almighty, and I will open the windows of heaven and pour out so much blessing that you won't have enough room for it.` },
{ l: 'Mark 4:19', t: `But worries of this world, the temptation of wealth, and other distractions choke the growth of the word, and it becomes unproductive.` },
{ l: 'Mark 10:23-25', t: `23Jesus looked around, and said to his disciples, “It's only with difficulty that wealthy people enter the kingdom of God!” The disciples were shocked at this. But Jesus went on, “My friends, it is difficult to enter God's kingdom. It's easier for a camel to go through the eye of a needle than for the rich to enter God's kingdom.”` },
{ l: 'Mark 10:29-30', t: `Jesus replied, “anyone who has left behind their home or brothers or sisters or mother or father or children or lands because of me, and for the sake of the good news, will receive in return in due course a hundred times as many homes and brothers and sisters and children and lands—as well as persecution. In the world to come they will receive eternal life.` },
{ l: 'Matthew 6:8', t: `Your Father knows what you need even before you ask him.` },
{ l: 'Matthew 6:11', t: `Please give to us today the food we need. (daily bread)` },
{ l: 'Matthew 6:19-20', t: `Don't pile up wealth here on earth where moths and rust ruin it, and where thieves break in and steal it. Instead, you should store up your wealth in heaven, where moths and rust don't ruin it, and where thieves don't break in and steal it.` },
{ l: 'Matthew 6:24', t: `No one can serve two masters. Either you'll hate one and love the other, or you'll be devoted to one and despise the other. You can't serve both God and Money.` },
{ l: 'Matthew 6:25-33', t: `I'm telling you not to worry about your life. Don't worry about what to eat, or what to drink, or what clothes to put on. Isn't life more than food, and the body more than clothes? Look at the birds—they don't sow or reap or store food in barns, for your heavenly Father feeds them. Aren't you worth more than they are? Who of you by worrying can add a minute to your life? And why are you worried about clothes? Look at the beautiful flowers in the field. See how they grow: they don't work hard, they don't spin thread. But I tell you, not even Solomon in all his glory was dressed like one of these flowers. So if God decorates the fields like this, grass which is here today and tomorrow is thrown into the fire, won't he do much more for you, you people who trust so little? So don't worry, saying, ‘What shall we eat?’ or ‘What shall we drink?’ or ‘What shall we wear?’ These are all the things that the heathen chase after, but your heavenly Father knows everything you need. Seek his kingdom first, and his way of living right, and everything will be given to you.` },
{ l: 'Matthew 6:33', t: `Seek his kingdom first, and his way of living right, and everything will be given to you.` },
{ l: 'Matthew 10:9-10', t: `Don't carry any gold, silver, or copper coins in your pockets, or a bag for your journey, or two cloaks, or sandals, or a walking stick, for a worker deserves to be supported.` },
{ l: 'Matthew 13:22', t: `The seeds sown among thorns are people who hear the message, but then life's worries and the temptation of money choke the message so that they become fruitless.` },
{ l: 'Matthew 19:23-24', t: `“I tell you the truth,” Jesus said to his disciples, “rich people find it hard to enter the kingdom of heaven. I also tell you this: It's easier for a camel to pass through the eye of a needle than for a rich person to enter the kingdom of God.”` },
{ l: 'Matthew 19:29', t: `All those who because of me have left their homes, brothers, sisters, father, mother, children, and fields, will receive back a hundred times more, and will receive eternal life.` },
{ l: 'Matthew 25:20-21', t: `The one with five talents came and presented the other five talents. ‘Master,’ he said, ‘You gave me five talents. Look, I've made a profit of five talents.’ His master said to him, ‘You've done well—you are a good, faithful servant. You have proved yourself trustworthy over small things, so now I'm placing you in charge over many things. Be happy because I'm really pleased with you!’` },
{ l: 'Nehemiah 2:20', t: ` “The God of heaven, he will make sure we're successful. We, his servants, will begin rebuilding [Jerusalem's wall]` },
{ l: 'Nehemiah 9:20-21', t: `You gave your good Spirit to teach them. You did not stop feeding them with your manna, and you gave them water when they were thirsty. You took care of them for forty years in the desert. Their clothes didn't wear out, they didn't want for anything. Their feet didn't even swell up!` },
{ l: 'Nehemiah 9:25', t: `They captured fortified cities and fertile land. They took over houses full of valuable things, water cisterns, vineyards, olive groves, and many fruit trees. They ate until they were full, and grew fat. They were so happy at how good you were to them.` },
{ l: 'Numbers 6:22–26', t: `The Lord told Moses, “Tell Aaron and his sons: This is how you are to bless the Israelites. This is what they are to say: ‘May the Lord bless you and take care of you. May the Lord smile on you and be gracious to you. May the Lord watch over you and give you peace.’` },
{ l: 'Numbers 18:21–24', t: `I have given the Levites all the tithes in Israel as compensation for the service they provide in doing the work in the Tent of Meeting.` },
{ l: 'Philippians 4:6–7', t: `Don't worry about anything, but take everything to God in prayer, explaining your requests to him and thanking him for all he does. Then the peace that comes from God, which is better than we can ever imagine, will protect your thoughts and attitudes in Christ Jesus.` },
{ l: 'Philippians 4:12-13', t: `I'm used to having nothing, and I've experienced having plenty too. In every possible situation I've learned the secret of dealing with having plenty and going hungry, of being rich and of living in poverty: I can do anything through him who makes me strong!` },
{ l: 'Philippians 4:15-19', t: `You Philippians remember that right at the beginning of sharing the good news, when I left Macedonia, that yours was the only church that helped me financially. Even when I was in Thessalonica you helped me out not once but twice. Not that I'm looking for a donation—I'm looking for your “account” to increase in “profit.” For I have everything, more than I need! I'm thankful to receive from Epaphroditus the things you sent. They're like a sweet-smelling sacrifice that pleases God and that he approves of. My God will fill you with everything you need in accordance with his glorious wealth in Christ Jesus!` },
{ l: 'Proverbs 3:9–10', t: `Honor the Lord with your wealth and with the firstfruits of all the crops you grow. Then your barns will be filled with produce, and your vats will overflow with new wine.` },
{ l: 'Proverbs 3:16-17', t: `She [wisdom] offers long life in one hand, and riches and honor in the other. 17She brings true happiness, and leads to peaceful prosperity. ` },
{ l: 'Proverbs 8:18-22', t: `With me [wisdom] go riches and honor, lasting wealth and prosperity. The fruit I produce is better than gold, even pure gold, and my harvest is better than even the best silver. ... I grant wealth to those who love me; I fill their treasure storehouses. The Lord created me first of all; I was made before anything else.` },
{ l: 'Proverbs 10:3', t: `The Lord doesn't let good people go hungry` },
{ l: 'Proverbs 10:4', t: `Hard-working hands make you rich.` },
{ l: 'Proverbs 10:6', t: `Those who are good are blessed` },
{ l: 'Proverbs 10:15', t: `The wealth of the rich provides them protection, while the poverty of the poor ruins them.` },
{ l: 'Proverbs 10:22', t: `The Lord's blessing makes you rich, and he doesn't add any sadness to accompany it.` },
{ l: 'Proverbs 11:4', t: `Wealth won't help you on judgment day` },
{ l: 'Proverbs 11:24–25', t: `If you give generously you receive more, but if you keep back what you should give, you end up poor. If you're generous, you'll become rich.` },
{ l: 'Proverbs 11:28', t: `If you trust in your riches, you'll fall` },
{ l: 'Proverbs 12:11', t: `If you cultivate the land you'll have plenty of food, but if you chase after worthless things you're stupid.` },
{ l: 'Proverbs 13:11', t: `Wealth gained by fraud quickly disappears, but those who gather bit by bit prosper.` },
{ l: 'Proverbs 13:22', t: `Good people leave an inheritance to their grandchildren` },
{ l: 'Proverbs 13:23', t: `The unplowed ground of the poor could produce a lot of food, but it's stolen through injustice.` },
{ l: 'Proverbs 14:23-24', t: `There's profit in hard work, but just talking leads to poverty. The wise are rewarded with wealth` },
{ l: 'Proverbs 15:6', t: `There's plenty of treasure where good people live, but the income of the wicked brings them trouble.` },
{ l: 'Proverbs 15:16', t: `It's better to respect the Lord and only have a little than to have plenty of money and the trouble that comes with it.` },
{ l: 'Proverbs 16:3', t: `Trust whatever you do to the Lord, and your plans will be successful.` },
{ l: 'Proverbs 16:8', t: `Better to have just a little and be honest than to have a lot and be dishonest.` },
{ l: 'Proverbs 18:11', t: `Accurate scales and balances are important to the Lord. He has determined all the weights in the bag.` },
{ l: 'Proverbs 19:1', t: `Better to be poor but honest than stupid and tell lies.` },
{ l: 'Proverbs 19:4', t: `If you're rich, you get a lot of friends, but if you're poor, you lose any friends you had.` },
{ l: 'Proverbs 19:17', t: `If you're kind to the poor, you're lending to the Lord, and he will repay you well for what you've done.` },
{ l: 'Proverbs 21:5', t: `Those who plan ahead and work hard will have plenty, while those who act rashly end up poor.` },
{ l: 'Proverbs 21:17', t: `If you love pleasure you'll become poor` },
{ l: 'Proverbs 21:20', t: `The wise hold on to their wealth and olive oil, but stupid people use up everything they have.` },
{ l: 'Proverbs 22:1-2', t: `A good reputation is a much better choice than plenty of money; respect is better than silver and gold. The rich and the poor have this in common: the Lord created them all.` },
{ l: 'Proverbs 22:4', t: `The reward you receive for being humble and respecting the Lord is wealth, honor, and life.` },
{ l: 'Proverbs 22:9', t: `If you're generous, you'll be blessed, for you share your food with those in need.` },
{ l: 'Proverbs 22:16', t: `If you oppress the poor to make yourself rich, or if you're generous to the rich, you'll end up poor yourself.` },
{ l: 'Proverbs 23:4–5', t: `Don't wear yourself out trying to get rich—be wise enough not to bother! It disappears in the blink of an eye, suddenly growing wings and flying off into the sky like an eagle.` },
{ l: 'Proverbs 24:3-4', t: `A house is built by wisdom; its foundation is made secure through understanding. Its rooms are filled by knowledge with all kinds of valuable and beautiful objects.` },
{ l: 'Proverbs 27:23–24', t: `You should know the condition of your flocks really well and take good care of your herds, for wealth doesn't last forever—is a crown passed down through all generations?` },
{ l: 'Proverbs 28:8', t: `Anyone who gets rich through charging interest and profiteering is only storing it up for someone who is kind to the poor.` },
{ l: 'Proverbs 28:19-22', t: `If you cultivate the land you'll have plenty of food, but if you chase fantasies you'll end up with nothing. If you're trustworthy, you'll be richly rewarded; but if you try to get rich quick, you won't go unpunished. ... Envious people are in a rush to get rich; they don't realize they'll end up poor.` },
{ l: 'Proverbs 30:7–9', t: `God, I want to request two things from you. ... Don't make me poor or rich; just provide me with the food I need. Otherwise if I have plenty of money, I may give up on you, saying, “Who is the Lord?” while if I'm poor I may steal and bring the name of my God into disrepute.` },
{ l: 'Psalm 5:12', t: `For you, Lord, bless those who live right; you protect them with your shield of love.` },
{ l: 'Psalm 23:1', t: `The Lord is my shepherd, I have everything I need.` },
{ l: 'Psalm 24:1-5', t: `The earth is the Lord's, and everything that is in it belongs to him. The world is his, and everyone who lives there. ... They will take with them the blessing of the Lord, vindicated by the God who saves them.` },
{ l: 'Psalm 25:12-13', t: `Who are those who respect the Lord? He will show them the path to choose. They will continue to be prosperous, and their descendants will inherit the land.` },
{ l: 'Psalm 34:9-10', t: `Show your reverence for the Lord, you who are his holy people, for those who respect him have everything they need. Lions may grow weak and hungry, but those who trust in the Lord have all that is good.` },
{ l: 'Psalm 35:27', t: `How great is the Lord! He is happy when his servants live in peace and have what they need.` },
{ l: 'Psalm 36:7-8', t: `God, how priceless is your trustworthy love! Everyone can find protection under the shelter of your wings. They gain strength from the wonderful food you provide in your house; you give them drink from your refreshing river.` },
{ l: 'Psalm 37:3', t: `Trust in the Lord, and do good. Live in the land and feed on faithfulness.` },
{ l: 'Psalm 37:5', t: `Entrust all that you do to the Lord. Place your confidence in him and he will help you.` },
{ l: 'Psalm 37:16', t: `It's better to do right and only have a little, than to be wicked and rich.` },
{ l: 'Psalm 37:19', t: `Even in days of famine they will have plenty to eat.` },
{ l: 'Psalm 37:25', t: `Once I was young, and now I've grown old, yet I've never seen those who do right abandoned, nor their children having to beg for bread.` },
{ l: 'Psalm 41:1', t: `How happy are those who take care of the poor! When they are in trouble the Lord will save them.` },
{ l: 'Psalm 49:16-17', t: `Don't be disturbed when people become rich, filling their houses with possessions. For they won't take anything with them when they die; their wealth will not go down into the grave with them.` },
{ l: 'Psalm 52:7-8', t: `See what happens to those who don't go to God for help but instead rely on their great wealth and strength—which only brings their destruction! But I'm like an olive tree growing strongly in God's house. I trust in God's unfailing love forever and ever.` },
{ l: 'Psalm 62:10', t: `Don't trust in money made by extortion or robbery. Don't be proud of your wealth even if you are successful—don't make money what you live for.` },
{ l: 'Psalm 65:9-11', t: `You care for the earth and water it; you make it very productive. God, your river is full of water to grow the grain—this is what you have planned. You fill the plowed furrows with water, you soften the ridges; you bless the growing crops. You make the high point of the year a wonderful harvest, filling the wagons with good things.` },
{ l: 'Psalm 67:6-7', t: `The earth has produced its crops; and God, our God, has blessed us. God will bless us` },
{ l: 'Psalm 68:10', t: `Your people settled there, and because of your kindness, God, you looked after the poor.` },
{ l: 'Psalm 68:19', t: `May the Lord be blessed, for every day he carries our burdens.` },
{ l: 'Psalm 71:20-21', t: `You had me face many troubles and plenty of misery, but you will bring me back to life; you will raise me up from the depths of the earth. You will give me even greater prestige, and you will make me happy again.` },
{ l: 'Psalm 72:15–16', t: `May he [the king) live long! May the gold from Sheba be given to him. May people always pray for him and bless him all day long. May there be plenty of grain in the land, even growing on mountain-tops. May the fruit on the trees sway like the trees of Lebanon. May the people in the city flourish like grass in a field.` },
{ l: 'Psalm 81:10', t: `I am the Lord your God who brought you out of the land of Egypt. Open your mouth wide and I will fill it.` },
{ l: 'Psalm 81:16', t: `I (God) would feed you the best wheat and satisfy you with honey from the rock.` },
{ l: 'Psalm 84:11', t: `The Lord doesn't hold back anything good from those who do right.` },
{ l: 'Psalm 85:12', t: `The Lord will certainly give us all that is good, and our land will produce fine crops.` },
{ l: 'Psalm 90:17', t: `May our Lord God be pleased with us, blessing what we do, blessing what we do.` },
{ l: 'Psalm 92:12-14', t: `Those who live right flourish like a palm tree; they grow tall like a cedar tree in Lebanon. They are planted in the house of the Lord; they thrive in the courts of our God. Even when they are old they will still produce fruit, staying fresh and green.` },
{ l: 'Psalm 104:14–15', t: `You make the grass grow for the cattle, and plants for people to eat—crops produced by the earth for food, and wine to make them happy, olive oil to make their faces shine, and bread to make them strong.` },
{ l: 'Psalm 107:35-38', t: `He also turns around and makes pools of water in the desert, and makes water springs flow in a dry and dusty land. He brings hungry people to live there—a place they can build their cities. They sow their fields and plant their vineyards, producing a good harvest. He takes care of them, and their numbers increase dramatically—their cattle too!` },
{ l: 'Psalm 111:4-6', t: `He wants the wonderful things he has done to be remembered; the Lord is gracious and kind. He feeds those who respect him; he always remembers the agreement he made. He demonstrated to his people the powerful things he could do by giving them the lands of other nations.` },
{ l: 'Psalm 112:1–3', t: `Praise the Lord! Happy are those who respect the Lord, who love to do what he says! Their descendants will prosper in the land; the children of those who do good will be blessed. Their families will be wealthy; the good they do has eternal results.` },
{ l: 'Psalm 112:5-6', t: `Good things come to those who are generous in their lending and are honest in doing business. They will never fall. ` },
{ l: 'Psalm 115:13-15', t: `The Lord will bless all those who worship him, whoever they are. May the Lord be good to you, you and your children. May you be blessed by the Lord who made heaven and earth.` },
{ l: 'Psalm 118:25', t: `Lord, please save us! Lord, please make us successful!` },
{ l: 'Psalm 126:4–6', t: `Please return and help us again, Lord. Renew us like streams of water that renew the Negev desert. Those who sow in tears will reap with shouts of joy! Those who weep as they go out to sow their seed will be singing in celebration when they carry the harvest home.` },
{ l: 'Psalm 128:1-4', t: `Happy are all those who worship the Lord, everyone who follows his ways! You will eat what your own hands have produced. You will be happy and do well. Your wife will be like a fruitful vine growing in your home. Your children will be like the shoots of an olive tree around your table. This will certainly be the Lord's blessing on those who worship him.` },
{ l: 'Psalm 132:15', t: `I [Lord] will provide the people of the city with all they need; I will feed the poor.` },
{ l: 'Psalm 136:25', t: `To the one who provides food for every living creature.` },
{ l: 'Psalm 145:16', t: `You give generously and satisfy the needs of every living thing.` },
{ l: 'Revelation 3:17-18', t: `You say to yourselves, ‘I'm rich, I have wealth, and don't need anything.’ But you don't know that you are miserable and pitiful and poor and blind and naked. I advise you to buy from me gold refined by fire so you may be rich; and have white clothes so you can be properly dressed and you won't reveal your nakedness and shame; and ointment to put on your eyes so you can see.` },
{ l: 'Romans 8:28', t: `We know that in all things God works for the good of those who love him, those whom he has called to be part of his plan.` },
{ l: 'Romans 8:32', t: `God, who did not hold back his own Son, but gave him up for all of us, won't he also freely give us everything?` },
{ l: 'Romans 8:35', t: `Who can separate us from Christ's love? Can oppression, distress, or persecution? Or hunger, poverty, danger, or violence?` },
{ l: 'Romans 12:13', t: `Share in providing for the needs of God's people, and welcome strangers with hospitality.` },
{ l: 'Ruth 2:4', t: `Boaz arrived from Bethlehem, and said to the reapers, “May the Lord be with you!” They replied, “The Lord bless you!”` },
{ l: 'Zechariah 8:12', t: `They will sow in peace; the vine will produce grapes; the soil will grow crops and the heavens will water them. I will make sure this happens to all those who remain of this people.` },
{ l: 'Zechariah 10:8', t: `I will whistle to them and they will run to me. I will rescue them` },
];

// TODO badasses of the bible.

export const topics = [
    { id: 'healing', name: 'Healing', verses: healing },
    { id: 'spirit', name: 'Holy Spirit', verses: holySpiritAndSanctification },
    { id: 'blessing', name: 'Blessing', verses: blessing },
];
